name: Auto deployment

on:
  push:
    branches:
      - feature_auto_deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: FTP File synchronization📂
    #   uses: SamKirkland/FTP-Deploy-Action@4.3.2
    #   with:
    #     server: ${{ secrets.FTP_SERVER }}
    #     username: ${{ secrets.FTP_USERNAME }}
    #     password: ${{ secrets.FTP_PASSWORD }}

    - name: Check if .env file exists
      run: |
        if [ -f "/var/www/html/academix-learning-system-backend/.env" ]; then
          echo "File exists"
          cp /var/www/html/academix-learning-system-backend/.env $GITHUB_WORKSPACE/.env
        else
          echo "File does not exist"
        fi

    # Add additional steps if necessary

    - name: Deploy to server
      run: |
        # Delete existing app directory
        rm -rf /var/www/html/academix-learning-system-backend

        # Clone the project
        git clone https://github.com/Academix-DataDesign/academix-learning-system-backend.git /var/www/html/academix-learning-system-backend

        # Change directory to app
        cd /var/www/html/academix-learning-system-backend

        # Bring back the copied files if .env file exists
        if [ -f "$GITHUB_WORKSPACE/.env" ]; then
          cp $GITHUB_WORKSPACE/.env .
        fi

        # Install dependencies
        composer install --no-dev --prefer-dist --no-interaction

        # Set proper permissions (adjust as needed)
        chown -R www-data:www-data /var/www/html/academix-learning-system-backend/storage
        chown -R www-data:www-data /var/www/html/academix-learning-system-backend/bootstrap/cache
